terraform {
  required_providers {
    local = {
      source = "hashicorp/local"
    }
  }
}

provider "local" {}

resource "local_file" "hello" {
  filename = "${path.module}/output/hello.html"
  content  = <<-HTML
    <!DOCTYPE html>
    <html>
    <head><title>Hello Terraform</title></head>
    <body>
      <h1>Hello from Terraform!</h1>
      <p>This file was generated by Terraform using the local provider.</p>
    </body>
    </html>
  HTML
}
